= Управление индексами

OpenSearch Dashboards

Плагин управления индексами (IM) позволяет автоматизировать повторяющиеся задачи управления индексами и снижать затраты на хранение.

== Удаление данных

Чтобы удалить документ из индекса, используйте запрос DELETE:

[source, json]
----
DELETE movies/_doc/1
----

Операция DELETE увеличивает поле `_version`. Если вы добавите документ обратно с тем же идентификатором, поле `_version` увеличится снова. Это происходит потому, что OpenSearch удаляет `_source` документа, но сохраняет его метаданные.

== Следующие шаги

* Плагин управления состоянием индекса (ISM) позволяет автоматизировать повторяющиеся задачи управления индексами и снижать затраты на хранение. Для получения дополнительной информации см. раздел Управление состоянием индекса.
* Для получения инструкций по повторному индексированию данных см. раздел Повторное индексирование данных.

* Введение в индексирование
* Ограничения наименования для индексов
* Чтение данных
* Обновление данных
  * Пример ответа
* Удаление данных
* Следующие шаги

[NOTE]
====
Была ли эта страница полезной?

[ ] Да
[ ] Нет

Сообщите нам, почему

Осталось 350 символов

[Send]

Спасибо за ваш отзыв!

Есть вопрос? Задайте его на форуме OpenSearch.

Хотите внести вклад? Отредактируйте эту страницу или создайте задачу.
====

== Ссылки OpenSearch

=== Присоединяйтесь

* Кодекс поведения
* Форум
* Github
* Slack

=== Ресурсы

* О проекте
* График выпусков
* Политика обслуживания
* FAQ
* Отзывы
* Политика товарных знаков и брендов
* Конфиденциальность

=== Свяжитесь с нами

* Связаться
* Twitter
* LinkedIn
* YouTube
* Meetup
* Facebook

© Вкладчики OpenSearch, 2025. OpenSearch является зарегистрированным товарным знаком Amazon Web Services.

© 2005-2021 Django Software Foundation и отдельные вкладчики. Django является зарегистрированным товарным знаком Django Software Foundation. Этот веб-сайт был форкнут с BSD-лицензированного djangoproject.com, изначально разработанного Threespot & andrevv.
